language: generic
env:
  global:
    - TWINE_USERNAME=nikolasibalic
matrix:
    include:
        - os: linux
          sudo: required
          env: TOXENV=py27
        - os: linux
          sudo: required
          env: TOXENV=py3
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      if [[ "$TOXENV" == "py27" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi;
    else
      if [[ "$TOXENV" == "py27" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      fi;
    fi

  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH

script:
- if [[ "$TOXENV" == "py36" ]]; then
    conda create --yes -n py36 python=3.6;
    source activate py36;
  fi;
- conda update -n base --yes conda
- conda install --yes --file requirements.txt
- conda install --yes wheel
- python  -m compileall -f tas/*.py
- python setup.py build
- rm -rf build
- |
    if [[ $TRAVIS_TAG ]]; then
      conda install --yes twine;
      if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        python setup.py sdist bdist_wheel;
        python -m twine upload --repository-url https://upload.pypi.org/legacy/ dist/*.whl;
      else
        if [[ "$TOXENV" == "py3" ]]; then
          python setup.py sdist
          python -m twine upload --repository-url https://upload.pypi.org/legacy/ dist/*.tar.gz;
        fi;
      fi;
    fi
